# Generated by Django 4.1.2 on 2022-12-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.manager')),
            ],
            options={
                'db_table': 'managment',
            },
        ),
    ]
