# Generated by Django 4.1.2 on 2022-12-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('avarege', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
            ],
            options={
                'db_table': 'archeive',
            },
        ),
    ]
