# Generated by Django 4.1.2 on 2022-12-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mark',
            table='marks',
        ),
    ]
