# Generated by Django 4.1.2 on 2022-12-30 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('marks', '0002_alter_mark_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(default=333333, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub', to='subjects.subject'),
            preserve_default=False,
        ),
    ]
