# Generated by Django 4.1.2 on 2022-12-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('marks', '0003_mark_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='subject',
        ),
        migrations.AddField(
            model_name='mark',
            name='subject',
            field=models.ManyToManyField(related_name='sub', to='subjects.subject'),
        ),
    ]
