# Generated by Django 4.1.2 on 2022-12-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0006_alter_mark_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='subject',
        ),
    ]
