# Generated by Django 4.1.2 on 2022-12-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_sections', models.IntegerField(default=0)),
                ('number_of_books', models.IntegerField(default=0)),
                ('open_time', models.TimeField(auto_now=True)),
                ('close_time', models.TimeField(auto_now=True)),
            ],
            options={
                'db_table': 'libraries',
            },
        ),
    ]
