# Generated by Django 4.1.2 on 2022-12-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='image',
            field=models.ImageField(default=666, upload_to='static/'),
            preserve_default=False,
        ),
    ]
