# Generated by Django 4.1.2 on 2022-12-21 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_rooms', '0001_initial'),
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_rooms.class_room')),
                ('marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.mark')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
