# Generated by Django 4.1.2 on 2023-01-03 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(default=2222222, on_delete=django.db.models.deletion.CASCADE, to='parents.parent'),
            preserve_default=False,
        ),
    ]
