# Generated by Django 4.1.2 on 2023-01-04 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_rooms', '0003_class_room_teachers'),
        ('students', '0004_alter_student_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', related_query_name='student', to='class_rooms.class_room'),
        ),
    ]
