# Generated by Django 4.1.2 on 2022-12-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('class_rooms', '0002_remove_class_room_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_room',
            name='teachers',
            field=models.ManyToManyField(to='teachers.teacher'),
        ),
    ]
